export const SORT_TYPE = {
	QUICK: 'QUICK',
	MERGE: 'MERGE',
	BUBBLE: 'BUBBLE',
	SELECT: 'SELECT',
	INSERT: 'INSERT',
	HEAP: 'HEAP',
	SHELL: 'SHELL',
	SHAKER: 'SHAKER',
}

export const SORT_LIST = Object.keys(SORT_TYPE)
