export const SORT_TYPES = {
	QUICK: 'QUICK',
	MERGE: 'MERGE',
	BUBBLE: 'BUBBLE',
	SELECTION: 'SELECTION',
	INSERTION: 'INSERTION',
	HEAP: 'HEAP',
	SHELL: 'SHELL',
	COCKTAIL_SHAKER: 'COCKTAIL_SHAKER',
	BITONIC: 'BITONIC',
}
