export const ANIMATION_SPEED = 20

export const MAX_ARRAY_LENGTH = 25

export const MIN_ARRAY_LENGTH = 200

export const MIN_SLIDER_VALUE = 5

export const MAX_SLIDER_VALUE = 40

export const SORT_TYPES = {
	QUICK: 'QUICK',
	MERGE: 'MERGE',
	BUBBLE: 'BUBBLE',
	SELECTION: 'SELECTION',
	INSERTION: 'INSERTION',
	HEAP: 'HEAP',
	SHELL: 'SHELL',
	COCKTAIL_SHAKER: 'COCKTAIL_SHAKER',
	BITONIC: 'BITONIC',
}
