export const SORT_TYPE = {
	QUICK: 'QUICK',
	MERGE: 'MERGE',
	BUBBLE: 'BUBBLE',
	SELECTION: 'SELECTION',
	INSERTION: 'INSERTION',
	HEAP: 'HEAP',
	SHELL: 'SHELL',
	COCKTAIL_SHAKER: 'COCKTAIL_SHAKER',
}

export const SORT_TYPE_LIST = Object.keys(SORT_TYPE)
